name: Create ZIP Files and Release

on:
 push:
    branches:
      - main # Adjust this to the branch you want to trigger the workflow on

jobs:
 create_zips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make script executable
        run: chmod +x create_zips.sh

      - name: Run script to create ZIP files
        run: ./create_zips.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: chrome_extension.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: firefox_extension.zip

 create_release_and_upload_zips:
    needs: create_zips
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get Variables (Linux)
        run: |
          ls
          echo "TAG=$(echo $GITHUB_REF | sed 's/^refs\/heads\///')" >> $GITHUB_ENV
      - name: Upload chrome_extension.zip to Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: chrome_extension.zip
          asset_name: chrome_extension.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload firefox_extension.zip to Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: firefox_extension.zip
          asset_name: firefox_extension.zip
          tag: ${{ github.ref }}
          overwrite: true
