name: Create ZIP Files and Release

on:
 push:
    branches:
      - main # Adjust this to the branch you want to trigger the workflow on

jobs:
 create_zips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make script executable
        run: chmod +x create_zips.sh

      - name: Run script to create ZIP files
        run: ./create_zips.sh

 create_release_and_upload_zips:
    needs: create_zips
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload chrome_extension.zip to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: chrome_extension.zip
          asset_name: chrome_extension.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload firefox_extension.zip to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: firefox_extension.zip
          asset_name: firefox_extension.zip
          tag: ${{ github.ref }}
          overwrite: true
